#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT/.env"
ENV_EXAMPLE="$ROOT/.env.example"
PORT="${PORT:-8080}"
WS_URL="ws://localhost:${PORT}/sync"
START_SERVER=0
RESET_KEY=0

usage() {
  cat <<'EOF'
Usage: ./setup.sh [options]

Sets up sync-server dependencies, creates .env with API_KEY, and prints
Ruleon connection settings.

Options:
  --start       Start the server after setup
  --reset-key   Regenerate API_KEY in .env (overwrites existing key)
  -h, --help    Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --start) START_SERVER=1 ;;
    --reset-key) RESET_KEY=1 ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
  shift
done

find_node_bin_dir() {
  local major
  if command -v node >/dev/null 2>&1; then
    major="$(node -p "process.versions.node.split('.')[0]")"
    if [[ "$major" -ge 20 && "$major" -lt 24 ]]; then
      dirname "$(command -v node)"
      return 0
    fi
  fi

  if [[ -x "/opt/homebrew/opt/node@20/bin/node" ]]; then
    echo "/opt/homebrew/opt/node@20/bin"
    return 0
  fi

  if [[ -x "/usr/local/opt/node@20/bin/node" ]]; then
    echo "/usr/local/opt/node@20/bin"
    return 0
  fi

  if [[ -n "${NVM_DIR:-}" && -s "$NVM_DIR/nvm.sh" ]]; then
    # shellcheck disable=SC1090
    source "$NVM_DIR/nvm.sh"
    if nvm use 20 >/dev/null 2>&1; then
      dirname "$(command -v node)"
      return 0
    fi
  fi

  return 1
}

generate_api_key() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
    return 0
  fi
  # Fallback when openssl is unavailable
  node -e "console.log(require('crypto').randomBytes(24).toString('hex'))"
}

read_api_key_from_env() {
  if [[ ! -f "$ENV_FILE" ]]; then
    return 1
  fi
  grep -E '^API_KEY=' "$ENV_FILE" | head -n1 | cut -d= -f2- | tr -d '\r'
}

write_env_file() {
  local api_key="$1"
  cat >"$ENV_FILE" <<EOF
# Generated by sync-server/setup.sh — do not commit (.gitignore).
API_KEY=${api_key}
PORT=${PORT}
EOF
}

NODE_BIN_DIR="$(find_node_bin_dir || true)"
if [[ -z "$NODE_BIN_DIR" ]]; then
  cat >&2 <<'EOF'
Node.js 20–23 is required for sync-server.

Install Node 20, then re-run ./setup.sh:

  brew install node@20
  PATH="/opt/homebrew/opt/node@20/bin:$PATH" ./setup.sh

Or with nvm:

  nvm install 20
  nvm use 20
  ./setup.sh
EOF
  exit 1
fi

export PATH="$NODE_BIN_DIR:$PATH"

echo "→ Using Node $(node -v) from $NODE_BIN_DIR"
echo "→ Installing dependencies…"
npm install --prefix "$ROOT"

echo "→ Syncing database schema…"
npm run sync-schema --prefix "$ROOT"

API_KEY=""
if [[ -f "$ENV_FILE" && "$RESET_KEY" -eq 0 ]]; then
  API_KEY="$(read_api_key_from_env || true)"
fi

if [[ -z "$API_KEY" ]]; then
  API_KEY="$(generate_api_key)"
  write_env_file "$API_KEY"
  if [[ -f "$ENV_FILE" && "$RESET_KEY" -eq 1 ]]; then
    echo "→ Regenerated API_KEY in $ENV_FILE"
  else
    echo "→ Created $ENV_FILE with a new API_KEY"
  fi
else
  echo "→ Using existing API_KEY from $ENV_FILE (pass --reset-key to regenerate)"
fi

SCHEMA_VERSION="$(node -e "
  const fs = require('fs');
  const path = require('path');
  const { cryb64 } = require('@vlcn.io/ws-common');
  const schemaPath = path.join(process.argv[1], 'schemas', 'ruleon');
  const sql = fs.readFileSync(schemaPath, 'utf8');
  console.log(cryb64(sql).toString());
" "$ROOT" 2>/dev/null || echo "unknown")"

cat <<EOF

════════════════════════════════════════════════════════════
  Ruleon sync server — connection settings
════════════════════════════════════════════════════════════

  WebSocket URL : ${WS_URL}
  API key       : ${API_KEY}
  Schema version: ${SCHEMA_VERSION}

  In Ruleon app:
    Settings → Sync
      • Enable Synchronization: ON
      • WebSocket URL: ${WS_URL}
      • API key: ${API_KEY}
    Then click "Save & Restart"

  Quick-add (Inbox) API:
    POST http://localhost:${PORT}/api/inbox
    Header: X-API-Key: ${API_KEY}
    Body:   {"text":"Your capture here"}

  Example:
    curl -X POST http://localhost:${PORT}/api/inbox \\
      -H "Content-Type: application/json" \\
      -H "X-API-Key: ${API_KEY}" \\
      -d '{"text":"Buy milk"}'

  Start server:
    cd sync-server && npm start

  Or next time:
    ./setup.sh --start

════════════════════════════════════════════════════════════

EOF

if [[ "$START_SERVER" -eq 1 ]]; then
  echo "→ Starting sync server…"
  exec npm start --prefix "$ROOT"
fi
